stateDiagram-v2
  [*] --> RECEIVED
  RECEIVED --> RISK_REJECTED
  RECEIVED --> APPROVED
  APPROVED --> SUBMISSION_PENDING
  APPROVED --> CANCELED
  SUBMISSION_PENDING --> ACKNOWLEDGED
  SUBMISSION_PENDING --> REJECTED
  ACKNOWLEDGED --> PARTIALLY_FILLED
  ACKNOWLEDGED --> FILLED
  ACKNOWLEDGED --> CANCEL_PENDING
  ACKNOWLEDGED --> EXPIRED
  PARTIALLY_FILLED --> PARTIALLY_FILLED
  PARTIALLY_FILLED --> FILLED
  PARTIALLY_FILLED --> CANCEL_PENDING
  CANCEL_PENDING --> CANCELED
  CANCEL_PENDING --> PARTIALLY_FILLED
  CANCEL_PENDING --> FILLED
  RISK_REJECTED --> [*]
  REJECTED --> [*]
  CANCELED --> [*]
  EXPIRED --> [*]
  FILLED --> [*]
